# -*- coding: utf-8 -*-
"""Talent scourcing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hBGyhBWMAGO_vuQmBlFKfYftFqFkVTB2
"""



"""Background:

As a talent sourcing and management company, we are interested in finding talented individuals for sourcing these candidates to technology companies. Finding talented candidates is not easy, for several reasons. The first reason is one needs to understand what the role is very well to fill in that spot, this requires understanding the client’s needs and what they are looking for in a potential candidate. The second reason is one needs to understand what makes a candidate shine for the role we are in search for. Third, where to find talented individuals is another challenge.

The nature of our job requires a lot of human labor and is full of manual operations. Towards automating this process we want to build a better approach that could save us time and finally help us spot potential candidates that could fit the roles we are in search for. Moreover, going beyond that for a specific role we want to fill in we are interested in developing a machine learning powered pipeline that could spot talented individuals, and rank them based on their fitness.

We are right now semi-automatically sourcing a few candidates, therefore the sourcing part is not a concern at this time but we expect to first determine best matching candidates based on how fit these candidates are for a given role. We generally make these searches based on some keywords such as “full-stack software engineer”, “engineering manager” or “aspiring human resources” based on the role we are trying to fill in. These keywords might change, and you can expect that specific keywords will be provided to you.

Assuming that we were able to list and rank fitting candidates, we then employ a review procedure, as each candidate needs to be reviewed and then determined how good a fit they are through manual inspection. This procedure is done manually and at the end of this manual review, we might choose not the first fitting candidate in the list but maybe the 7th candidate in the list. If that happens, we are interested in being able to re-rank the previous list based on this information. This supervisory signal is going to be supplied by starring the 7th candidate in the list. Starring one candidate actually sets this candidate as an ideal candidate for the given role. Then, we expect the list to be re-ranked each time a candidate is starred.

**Data Description** :

The data comes from our sourcing efforts. We removed any field that could directly reveal personal details and gave a unique identifier for each candidate.

**Attributes**:
id : unique identifier for candidate (numeric)

job_title : job title for candidate (text)

location : geographical location for candidate (text)

connections: number of connections candidate has, 500+ means over 500 (text)

**Output (desired target)**:
fit - how fit the candidate is for the role? (numeric, probability between 0-1)

Keywords: “Aspiring human resources” or “seeking human resources”

Download Data:

https://docs.google.com/spreadsheets/d/117X6i53dKiO7w6kuA1g1TpdTlv1173h_dPlJt5cNNMU/edit?usp=sharing

**Goal(s)**:

Predict how fit the candidate is based on their available information (variable fit)

Success Metric(s):

Rank candidates based on a fitness score.

Re-rank candidates when a candidate is starred.

Current Challenges:

We are interested in a robust algorithm, tell us how your solution works and show us how your ranking gets better with each starring action.

How can we filter out candidates which in the first place should not be in this list?

Can we determine a cut-off point that would work for other roles without losing high potential candidates?

Do you have any ideas that we should explore so that we can even automate this procedure to prevent human bias?
"""

from google.colab import drive
drive.mount('/content/drive')

data= pd.read_csv('/content/drive/MyDrive/Colab Notebooks/potential-talents - Aspiring human resources - seeking human resources.csv')

df=data.copy()

df.head()

df.shape

df.info()

"""* •	The fit column is entirely null (0 non-null counts), which means it contains no data.
* Connection column is object data type.
"""

df.describe().T

df.describe(include='object').T

"""* There are 104 entries, but only 52 unique job titles. The top job titles like "2019 C.T. Bauer College of Business Graduate..." 7 times
* There are 104 entries with 41 unique locations. "Kanada" (Canada) is the most frequent location with 12 occurrences
* connection column has 104 entries and 33 unique values. The most frequent value is "500+" (44 times), which represents candidates with over 500 connections.
"""

df.isnull().sum()

print("\n2. Categorical Columns:")
print("\nValue counts for 'job_title' column (top 10):")
print(df['job_title'].value_counts().head(10))

print("\nValue counts for 'location' column (top 10):")
print(df['location'].value_counts().head(10))

print("\nValue counts for 'connection' column:")
print(df['connection'].value_counts())

plt.figure(figsize=(8, 6))
sns.countplot(data=df, x='connection', order=df['connection'].value_counts().index)
plt.title('Distribution of Connections')
plt.xlabel('Connections')
plt.ylabel('Count')
plt.show()

# Converting the 'connection' column to a numerical format
df['connection'] = df['connection'].str.replace('500+', '500').astype(int)

print(df['connection'].value_counts())
print(df['connection'].dtype)



"""# **Encoding**

## Word2Vec
"""

# Install gensim if not already installed
!pip install gensim

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
import gensim.models
import numpy as np # numpy is used for np.mean and np.zeros

# Download necessary NLTK data (if not already downloaded)
try:
    nltk.data.find('tokenizers/punkt')
except LookupError:
    nltk.download('punkt')
try:
    nltk.data.find('corpora/stopwords')
except LookupError:
    nltk.download('stopwords')
try:
    nltk.data.find('corpora/wordnet')
except LookupError:
    nltk.download('wordnet')
try:
    # Explicitly download 'punkt_tab' as suggested by the error
    nltk.data.find('tokenizers/punkt_tab')
except LookupError:
    nltk.download('punkt_tab')

# Initialize lemmatizer and stopwords
# It initializes a WordNetLemmatizer to reduce words to their base form (e.g., 'running' to 'run') and loads a set of common English stop_words (like 'the', 'is', 'a') that are usually removed during text processing
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def preprocess_text(text):
    text = str(text).lower()  # Convert to string and lowercase
    tokens = word_tokenize(text)  # Tokenize
    # Remove stopwords, lemmatize, and remove non-alphabetic tokens
    tokens = [lemmatizer.lemmatize(word) for word in tokens if word.isalpha() and word not in stop_words]
    return tokens

# Apply preprocessing to the 'job_title' column
df['processed_job_title'] = df['job_title'].apply(preprocess_text)

# Train Word2Vec model
# min_count: Ignores all words with total frequency lower than this. 2 is a good starting point.
# vector_size: Dimensionality of the word vectors.
# window: Maximum distance between the current and predicted word within a sentence.
# workers: Use these many worker threads to train the model (=faster training with multicore machines).
# sg: Training algorithm: 1 for skip-gram; 0 for CBOW.

word2vec_model = gensim.models.Word2Vec(sentences=df['processed_job_title'],
                                        vector_size=100,
                                        window=5,
                                        min_count=2,
                                        workers=4,
                                        sg=0)



# Function to create document embedding by averaging word vectors
def get_document_embedding(tokens, model):
    vectors = [model.wv[word] for word in tokens if word in model.wv]
    if vectors:
        return np.mean(vectors, axis=0)
    else:
        return np.zeros(model.vector_size) # Return a zero vector if no words are in the vocabulary
# Apply the get_average_embedding function to each list of tokens
df['job_title_embedding'] = df['processed_job_title'].apply(lambda tokens: get_document_embedding(tokens, word2vec_model))
df[['job_title', 'job_title_embedding']].head()

from sklearn.metrics.pairwise import cosine_similarity

def recommend_job_titles(query_job_title, df, word2vec_model, top_n=10):
    # Preprocess the query job title
    processed_query = preprocess_text(query_job_title)

    # Get embedding for the query
    query_embedding = get_document_embedding(processed_query, word2vec_model)

    # Ensure query_embedding is a 2D array for cosine_similarity
    query_embedding = query_embedding.reshape(1, -1)

    # Convert the list of embeddings to a 2D numpy array
    job_title_vectors = np.array(df['job_title_embedding'].tolist())

    # Calculate cosine similarity between query and all job titles
    similarities = cosine_similarity(query_embedding, job_title_vectors)[0]

    # Create a DataFrame to store results
    recommendations_df = df.copy()
    recommendations_df['similarity'] = similarities

    # Sort by similarity in descending order
    recommendations_df = recommendations_df.sort_values(by='similarity', ascending=False)

    # Filter out the query itself if it's an exact match and select relevant columns
    recommendations_df = recommendations_df[recommendations_df['job_title'].str.lower() != query_job_title.lower()]

    return recommendations_df[['job_title', 'location', 'connection', 'similarity']].head(top_n)

# Example usage:
query = "Aspiring Human Resources"
recommended_jobs = recommend_job_titles(query, df, word2vec_model, top_n=10)

print(f"Recommendations for '{query}':\n")
display(recommended_jobs)

"""* the output shows several entries for "Aspiring Human Resources Specialist," all with a high similarity score of 0.885. This indicates that our word embedding model effectively captured the close semantic relationship between the query and this particular job title."""



"""## FastText"""

from gensim.models import FastText

# Train FastText model
# min_count: Ignores all words with total frequency lower than this. 2 is a good starting point.
# vector_size: Dimensionality of the word vectors.
# window: Maximum distance between the current and predicted word within a sentence.
# workers: Use these many worker threads to train the model (=faster training with multicore machines).
# sg: Training algorithm: 1 for skip-gram; 0 for CBOW. FastText often performs well with skip-gram (sg=1).

fasttext_model = FastText(sentences=df['processed_job_title'],
                          vector_size=100,
                          window=5,
                          min_count=2,
                          workers=4,
                          sg=1) # sg=1 for skip-gram, often preferred for FastText

# Function to create document embedding by averaging word vectors (similar to Word2Vec)
def get_fasttext_document_embedding(tokens, model):
    vectors = [model.wv[word] for word in tokens if word in model.wv]
    if vectors:
        return np.mean(vectors, axis=0)
    else:
        return np.zeros(model.vector_size) # Return a zero vector if no words are in the vocabulary

# Apply the get_fasttext_document_embedding function to each list of tokens
df['job_title_fasttext_embedding'] = df['processed_job_title'].apply(lambda tokens: get_fasttext_document_embedding(tokens, fasttext_model))
df[['job_title', 'job_title_fasttext_embedding']].head()

def recommend_job_titles_fasttext(query_job_title, df, fasttext_model, top_n=10):
    # Preprocess the query job title
    processed_query = preprocess_text(query_job_title)

    # Get embedding for the query
    query_embedding = get_fasttext_document_embedding(processed_query, fasttext_model)

    # Ensure query_embedding is a 2D array for cosine_similarity
    query_embedding = query_embedding.reshape(1, -1)

    # Convert the list of embeddings to a 2D numpy array
    job_title_vectors = np.array(df['job_title_fasttext_embedding'].tolist())

    # Calculate cosine similarity between query and all job titles
    similarities = cosine_similarity(query_embedding, job_title_vectors)[0]

    # Create a DataFrame to store results
    recommendations_df = df.copy()
    recommendations_df['similarity'] = similarities

    # Sort by similarity in descending order
    recommendations_df = recommendations_df.sort_values(by='similarity', ascending=False)

    # Filter out the query itself if it's an exact match and select relevant columns
    recommendations_df = recommendations_df[recommendations_df['job_title'].str.lower() != query_job_title.lower()]

    return recommendations_df[['job_title', 'location', 'connection', 'similarity']].head(top_n)

# Example usage with FastText:
query_fasttext = "Aspiring Human Resources"
recommended_jobs_fasttext = recommend_job_titles_fasttext(query_fasttext, df, fasttext_model, top_n=10)

print(f"Recommendations for '{query_fasttext}' using FastText:")
display(recommended_jobs_fasttext)

"""* the similarity scores for FastText (e.g., 0.935) are generally higher than those observed with Word2Vec (e.g., 0.885) for similar job titles. This can indicate that FastText, by considering character n-grams, might capture nuances or handle variations in job titles more effectively, leading to potentially stronger semantic matches.

## GLOVE
"""

import gensim.downloader as api

# Download a pre-trained GloVe model. This can take some time.
# We'll use a smaller version (50-dimensional vectors) for demonstration.
print("Downloading GloVe model... This may take a few minutes.")
try:
    glove_model = api.load("glove-wiki-gigaword-50")
    print("GloVe model downloaded successfully.")
except Exception as e:
    print(f"Error downloading GloVe model: {e}")
    print("Please ensure you have an active internet connection or try a different model.")
    glove_model = None # Set to None if download fails


# Function to create document embedding by averaging word vectors from GloVe
def get_glove_document_embedding(tokens, model):
    if model is None: # Handle case where model download failed
        return np.zeros(50) # Return a zero vector of appropriate size
    vectors = [model[word] for word in tokens if word in model.key_to_index]
    if vectors:
        return np.mean(vectors, axis=0)
    else:
        # Return a zero vector if no words are in the vocabulary or model is None
        return np.zeros(model.vector_size if model else 50)

# Apply the get_glove_document_embedding function to each list of tokens
if glove_model:
    df['job_title_glove_embedding'] = df['processed_job_title'].apply(lambda tokens: get_glove_document_embedding(tokens, glove_model))
    print(df[['job_title', 'job_title_glove_embedding']].head())
else:
    print("GloVe model not available. Cannot create embeddings.")
    df['job_title_glove_embedding'] = [np.zeros(50)] * len(df) # Add a dummy column to avoid errors

def recommend_job_titles_glove(query_job_title, df, glove_model, top_n=10):
    if glove_model is None:
        print("GloVe model is not loaded. Cannot provide recommendations.")
        return pd.DataFrame(columns=['job_title', 'location', 'connection', 'similarity'])

    # Preprocess the query job title
    processed_query = preprocess_text(query_job_title)

    # Get embedding for the query
    query_embedding = get_glove_document_embedding(processed_query, glove_model)

    # Ensure query_embedding is a 2D array for cosine_similarity
    query_embedding = query_embedding.reshape(1, -1)

    # Filter out rows where job_title_glove_embedding is all zeros (if any failed to get embeddings)
    valid_embeddings_df = df[df['job_title_glove_embedding'].apply(lambda x: not np.all(x == 0))].copy()

    if valid_embeddings_df.empty:
        print("No valid GloVe embeddings found for recommendations.")
        return pd.DataFrame(columns=['job_title', 'location', 'connection', 'similarity'])

    # Convert the list of embeddings to a 2D numpy array
    job_title_vectors = np.array(valid_embeddings_df['job_title_glove_embedding'].tolist())

    # Calculate cosine similarity between query and all job titles
    similarities = cosine_similarity(query_embedding, job_title_vectors)[0]

    # Create a DataFrame to store results
    recommendations_df = valid_embeddings_df.copy()
    recommendations_df['similarity'] = similarities

    # Sort by similarity in descending order
    recommendations_df = recommendations_df.sort_values(by='similarity', ascending=False)

    # Filter out the query itself if it's an exact match and select relevant columns
    recommendations_df = recommendations_df[recommendations_df['job_title'].str.lower() != query_job_title.lower()]

    return recommendations_df[['job_title', 'location', 'connection', 'similarity']].head(top_n)

# Example usage with GloVe:
query_glove = "Aspiring Human Resources"
recommended_jobs_glove = recommend_job_titles_glove(query_glove, df, glove_model, top_n=10)

print(f"\nRecommendations for '{query_glove}' using GloVe:")
display(recommended_jobs_glove)

"""# BERT"""

!pip install transformers torch

from transformers import BertTokenizer, BertModel
import torch

# Load pre-trained BERT model and tokenizer
print("Loading BERT tokenizer and model...")
tokenizer = BertTokenizer.from_pretrained('distilbert-base-uncased')
model = BertModel.from_pretrained('distilbert-base-uncased')
print("BERT model loaded successfully.")

# Function to get BERT embeddings for a given text
def get_bert_document_embedding(text, tokenizer, model):
    inputs = tokenizer(text, return_tensors='pt', truncation=True, padding=True, max_length=128)
    with torch.no_grad():
        outputs = model(**inputs)
    # Use the mean of the last hidden states as the document embedding
    # Or, you can use the [CLS] token embedding: outputs.last_hidden_state[:, 0, :].squeeze().numpy()
    return outputs.last_hidden_state.mean(dim=1).squeeze().numpy()

# Apply the get_bert_document_embedding function to the 'job_title' column
print("Generating BERT embeddings for job titles...")
df['job_title_bert_embedding'] = df['job_title'].apply(lambda x: get_bert_document_embedding(x, tokenizer, model))
print("BERT embeddings generated.")

df[['job_title', 'job_title_bert_embedding']].head()

def recommend_job_titles_bert(query_job_title, df, tokenizer, model, top_n=10):
    # Get embedding for the query
    query_embedding = get_bert_document_embedding(query_job_title, tokenizer, model)

    # Ensure query_embedding is a 2D array for cosine_similarity
    query_embedding = query_embedding.reshape(1, -1)

    # Convert the list of embeddings to a 2D numpy array
    job_title_vectors = np.array(df['job_title_bert_embedding'].tolist())

    # Calculate cosine similarity between query and all job titles
    similarities = cosine_similarity(query_embedding, job_title_vectors)[0]

    # Create a DataFrame to store results
    recommendations_df = df.copy()
    recommendations_df['similarity'] = similarities

    # Sort by similarity in descending order
    recommendations_df = recommendations_df.sort_values(by='similarity', ascending=False)

    # Filter out the query itself if it's an exact match and select relevant columns
    recommendations_df = recommendations_df[recommendations_df['job_title'].str.lower() != query_job_title.lower()]

    return recommendations_df[['job_title', 'location', 'connection', 'similarity']].head(top_n)

# Example usage with BERT:
query_bert = "Aspiring Human Resources"
recommended_jobs_bert = recommend_job_titles_bert(query_bert, df, tokenizer, model, top_n=10)

print(f"\nRecommendations for '{query_bert}' using BERT:")
display(recommended_jobs_bert)

"""## SBERT"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer

# Load a pre-trained SBERT model
# 'all-MiniLM-L6-v2' is a good general-purpose model
print("Loading SBERT model...")
sbert_model = SentenceTransformer('all-MiniLM-L6-v2')
print("SBERT model loaded successfully.")

# Function to get SBERT embeddings for a given text
def get_sbert_document_embedding(text, model):
    return model.encode(text, convert_to_numpy=True)

# Apply the get_sbert_document_embedding function to the 'job_title' column
print("Generating SBERT embeddings for job titles...")
df['job_title_sbert_embedding'] = df['job_title'].apply(lambda x: get_sbert_document_embedding(x, sbert_model))
print("SBERT embeddings generated.")

df[['job_title', 'job_title_sbert_embedding']].head()

def recommend_job_titles_sbert(query_job_title, df, sbert_model, top_n=10):
    # Get embedding for the query
    query_embedding = get_sbert_document_embedding(query_job_title, sbert_model)

    # Ensure query_embedding is a 2D array for cosine_similarity
    query_embedding = query_embedding.reshape(1, -1)

    # Convert the list of embeddings to a 2D numpy array
    job_title_vectors = np.array(df['job_title_sbert_embedding'].tolist())

    # Calculate cosine similarity between query and all job titles
    similarities = cosine_similarity(query_embedding, job_title_vectors)[0]

    # Create a DataFrame to store results
    recommendations_df = df.copy()
    recommendations_df['similarity'] = similarities

    # Sort by similarity in descending order
    recommendations_df = recommendations_df.sort_values(by='similarity', ascending=False)

    # Filter out the query itself if it's an exact match and select relevant columns
    recommendations_df = recommendations_df[recommendations_df['job_title'].str.lower() != query_job_title.lower()]

    return recommendations_df[['job_title', 'location', 'connection', 'similarity']].head(top_n)

# Example usage with SBERT:
query_sbert = "Aspiring Human Resources"
recommended_jobs_sbert = recommend_job_titles_sbert(query_sbert, df, sbert_model, top_n=10)

print(f"\nRecommendations for '{query_sbert}' using SBERT:")
display(recommended_jobs_sbert)